spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:C:\Users\Shiyo\Desktop\Java\teach\run\demo.db
server:
  port: 8080


mybatis-plus:
  configuration:
  map-underscore-to-camel-case: true
  mapper-locations=classpath: src/main/java/org/example/server/mapper/**.xml

mybatis:
    mapper-locations=classpath: src/main/java/classes/org/example/server/mapper/**.xml
