spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:C:\Users\Shiyo\Desktop\JavaCD\server\src\main\resources\db\demo.db
    username:
    password:
server:
  port: 8080


mybatis-plus:
  configuration:
  map-underscore-to-camel-case: true
